// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Kuis bertenaga AI tentang evolusi web yang memberikan petunjuk.
 *
 * - webEvolutionQuiz - Fungsi yang memulai kuis evolusi web.
 * - WebEvolutionQuizInput - Tipe input untuk fungsi webEvolutionQuiz.
 * - WebEvolutionQuizOutput - Tipe kembalian untuk fungsi webEvolutionQuiz.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const WebEvolutionQuizInputSchema = z.object({
  question: z.string().describe('Pertanyaan saat ini yang diajukan.'),
  userAnswer: z.string().optional().describe('Jawaban yang diberikan pengguna untuk pertanyaan saat ini, jika ada.'),
  hintRequest: z.boolean().optional().describe('Apakah pengguna telah meminta petunjuk untuk pertanyaan saat ini.'),
  quizHistory: z.array(z.object({
    question: z.string(),
    userAnswer: z.string().optional(),
    isCorrect: z.boolean().optional(),
    hintGiven: z.boolean().optional(),
  })).optional().describe('Riwayat kuis, termasuk pertanyaan sebelumnya, jawaban, dan kebenarannya.'),
});
export type WebEvolutionQuizInput = z.infer<typeof WebEvolutionQuizInputSchema>;

const WebEvolutionQuizOutputSchema = z.object({
  question: z.string().describe('Pertanyaan berikutnya dalam kuis.'),
  hint: z.string().optional().describe('Petunjuk untuk membantu pengguna menjawab pertanyaan, jika diminta dan sesuai.'),
  isCorrect: z.boolean().optional().describe('Apakah jawaban pengguna benar.'),
  explanation: z.string().optional().describe('Penjelasan dari jawaban yang benar.'),
  quizComplete: z.boolean().describe('Apakah kuis sudah selesai.'),
});
export type WebEvolutionQuizOutput = z.infer<typeof WebEvolutionQuizOutputSchema>;

export async function webEvolutionQuiz(input: WebEvolutionQuizInput): Promise<WebEvolutionQuizOutput> {
  return webEvolutionQuizFlow(input);
}

const prompt = ai.definePrompt({
  name: 'webEvolutionQuizPrompt',
  input: {schema: WebEvolutionQuizInputSchema},
  output: {schema: WebEvolutionQuizOutputSchema},
  prompt: `Anda adalah master kuis bertenaga AI yang berspesialisasi dalam evolusi web (Web1, Web2, Web3).

  Tujuan Anda adalah menguji pengguna dan membantu mereka belajar tentang evolusi web. Anda harus memberikan pertanyaan yang menarik dan informatif.

  Jika pengguna telah meminta petunjuk (hintRequest bernilai true), berikan petunjuk yang bermanfaat terkait dengan pertanyaan saat ini, tetapi hanya jika sesuai. Berikan secara ringkas.

  Jika pengguna telah memberikan jawaban (userAnswer ada), evaluasi kebenarannya dan berikan umpan balik. Sertakan penjelasan dari jawaban yang benar.

  Pertahankan nada percakapan yang ramah dan memberi semangat.

  Pertimbangkan riwayat kuis untuk menyesuaikan tingkat kesulitan dan menghindari pengulangan pertanyaan.

  Kuis harus terdiri dari maksimal 5 pertanyaan.

  Pertanyaan Saat Ini: {{{question}}}
  Jawaban Pengguna: {{{userAnswer}}}
  Petunjuk Diminta: {{{hintRequest}}}
  Riwayat Kuis: {{{quizHistory}}}
  Format keluaran: JSON.
  `,
});

const webEvolutionQuizFlow = ai.defineFlow(
  {
    name: 'webEvolutionQuizFlow',
    inputSchema: WebEvolutionQuizInputSchema,
    outputSchema: WebEvolutionQuizOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
